---
- hosts: chromebook1
  become: yes
  tasks:
    - name: set timezone to Asia/Tokyo
      timezone:
        name: Asia/Tokyo

    - name: apt update
      apt: 
        update_cache: 'yes'

    - name: apt upgrade
      apt:
        upgrade: 'yes'

    - name: blockinfile to .bashrc
      blockinfile:
        path: /root/.bashrc
        create: 'yes'
        marker: "# {mark} ANSIBLE Fish-shell basic setup."
        block: "{{item}}"
      with_file:
        - ubuntu_server/dotfiles/.bashrc
    
    - name: add .bash_hstn
      copy:
        src: ubuntu_server/dotfiles/.bash_hstn
        dest: /root/.bash_hstn

    - name: add .vimrc
      copy:
        src: ubuntu_server/dotfiles/.vimrc
        dest: /root/.vimrc
    
    - name: add .vimrc to sho
      copy:
        src: ubuntu_server/dotfiles/.vimrc
        dest: /home/sho/.vimrc
        owner: 'sho'
        group: 'sho'

    - name: apt-get install modules 1
      apt:
        name:
          - git
          - vim
          - lm-sensors
          - smokeping
          - fping

    - name: apt-get install modules 2
      apt:
        name:
          - zlib1g-dev
          - gcc
          - make
          - autoconf
          - autogen
          - automake
          - pkg-config
          - uuid-dev

    - name: copy smokeping/config.d/Probes
      copy:
        src: ubuntu_server/smokeping/config.d/Probes
        dest: /etc/smokeping/config.d/Probes
        backup: 'yes'

    - name: copy smokeping/config.d/Targets
      copy:
        src: ./ubuntu_server/smokeping/config.d/Targets
        dest: /etc/smokeping/config.d/Targets
        backup: 'yes'
    
    - name: restart smokeping
      systemd:
        name: smokeping.service
        state: restarted
        enabled: 'yes'

    - name: apt-get install apache2
      apt:
        name:
          - apache2

    - name: delete unuse apache2 conf
      shell: rm -f /etc/apache2/conf-available/*
      args:
        warn: false

    - name: disable unuse apache2 conf symlinks
      shell: rm -f /etc/apache2/conf-enabled/*
      args:
        warn: false

    - name: copy apache2 conf-available
      copy:
        src: ./ubuntu_server/apache2/etc/apache2/conf-available/{{ item }}
        dest: /etc/apache2/conf-available/
      with_items:
        - security.conf
        - server-cgi-bin.conf
        - smokeping.conf

    - name: enable apache2 conf-available
      shell: ln -s /etc/apache2/conf-available/{{ item }} /etc/apache2/conf-enabled/{{ item }}
      args:
        warn: false
      with_items:
        - security.conf
        - server-cgi-bin.conf
        - smokeping.conf

    - name: copy apache2 sites-available
      copy:
        src: ./ubuntu_server/apache2/etc/apache2/sites-available/{{ item }}
        dest: /etc/apache2/sites-available/
      with_items:
        - 000-default.conf
        - default-ssl.conf

    - name: restart apache2
      systemd:
        name: apache2.service
        state: restarted
        enabled: 'yes'

    - name: apt-get install netdata
      apt:
        name:
        - netdata
    
    - name: copy netdata/etc/netdata/netdata.conf
      copy:
        src: ./ubuntu_server/netdata/etc/netdata/netdata.conf
        dest: /etc/netdata/netdata.conf

    - name: restart netdata
      systemd:
        name: netdata.service
        state: restarted
        enabled: 'yes'
